export const url =
  process.env.NODE_ENV !== "production" ? "http://localhost:5000/api" : "url";

export const LOCAL_STORAGE_TOKEN_NAME = "lvtn";

export const DATA_LOADED_FAIL = "DATA_LOADED_FAIL";
export const DATA_LOADED_SUCCESS = "DATA_LOADED_SUCCESS";
export const CONFIGTYPE_LOADED_FAIL = "CONFIGTYPE_LOADED_FAIL";
export const CONFIGTYPE_LOADED_SUCCESS = "CONFIGTYPE_LOADED_SUCCESS";
export const ADD_DEVICE = "ADD_DEVICE";
export const CONFIGDATA_LOADED_FAIL = "CONFIGDATA_LOADED_FAIL";
export const CONFIGDATA_LOADED_SUCCESS = "CONFIGDATA_LOADED_SUCCESS";
export const ADD_CONFIGDATA = "ADD_CONFIGDATA";
export const STATUS_LOADED_FAIL = "STATUS_LOADED_FAIL";
export const STATUS_LOADED_SUCCESS = "STATUS_LOADED_SUCCESS";
export const ADD_CONFIGTYPE = "ADD_CONFIGTYPE";
export const DELETE_CONFIGTYPE = "DELETE_CONFIGTYPE";
export const FIND_CONFIGTYPE = "FIND_CONFIGTYPE";
export const UPDATE_CONFIGTYPE = "UPDATE_CONFIGTYPE";
export const TOTALVOLUME_LOADED_FAIL = "TOTALVOLUME_LOADED_FAIL";
export const TOTALVOLUME_LOADED_SUCCESS = "TOTALVOLUME_LOADED_SUCCESS";
export const SETVOLUME_LOADED_FAIL = "SETVOLUME_LOADED_FAIL";
export const SETVOLUME_LOADED_SUCCESS = "SETVOLUME_LOADED_SUCCESS";
export const ADD_SETVOLUME = "ADD_SETVOLUME";
export const FIND_SETVOLUME = "FIND_SETVOLUME";
export const UPDATE_SETVOLUME = "UPDATE_SETVOLUME";
export const TYPEMODAL_LOADED_FAIL = "TYPEMODAL_LOADED_FAIL";
export const TYPEMODAL_LOADED_SUCCESS = "TYPEMODAL_LOADED_SUCCESS";
export const FIND_CONFIGTYPEMODAL = "FIND_CONFIGTYPEMODAL";
